# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jeje/clones/CustomVonNeumannMachine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jeje/clones/CustomVonNeumannMachine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeje/clones/CustomVonNeumannMachine/CMakeFiles /home/jeje/clones/CustomVonNeumannMachine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeje/clones/CustomVonNeumannMachine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CustomVonNeumannMachine

# Build rule for target.
CustomVonNeumannMachine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CustomVonNeumannMachine
.PHONY : CustomVonNeumannMachine

# fast build rule for target.
CustomVonNeumannMachine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/build
.PHONY : CustomVonNeumannMachine/fast

#=============================================================================
# Target rules for targets named Assembler

# Build rule for target.
Assembler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Assembler
.PHONY : Assembler

# fast build rule for target.
Assembler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/build
.PHONY : Assembler/fast

assembler/assembler.o: assembler/assembler.cpp.o
.PHONY : assembler/assembler.o

# target to build an object file
assembler/assembler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/assembler/assembler.cpp.o
.PHONY : assembler/assembler.cpp.o

assembler/assembler.i: assembler/assembler.cpp.i
.PHONY : assembler/assembler.i

# target to preprocess a source file
assembler/assembler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/assembler/assembler.cpp.i
.PHONY : assembler/assembler.cpp.i

assembler/assembler.s: assembler/assembler.cpp.s
.PHONY : assembler/assembler.s

# target to generate assembly for a file
assembler/assembler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/assembler/assembler.cpp.s
.PHONY : assembler/assembler.cpp.s

src/PCB.o: src/PCB.cpp.o
.PHONY : src/PCB.o

# target to build an object file
src/PCB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/PCB.cpp.o
.PHONY : src/PCB.cpp.o

src/PCB.i: src/PCB.cpp.i
.PHONY : src/PCB.i

# target to preprocess a source file
src/PCB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/PCB.cpp.i
.PHONY : src/PCB.cpp.i

src/PCB.s: src/PCB.cpp.s
.PHONY : src/PCB.s

# target to generate assembly for a file
src/PCB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/PCB.cpp.s
.PHONY : src/PCB.cpp.s

src/core.o: src/core.cpp.o
.PHONY : src/core.o

# target to build an object file
src/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/core.cpp.o
.PHONY : src/core.cpp.o

src/core.i: src/core.cpp.i
.PHONY : src/core.i

# target to preprocess a source file
src/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/core.cpp.i
.PHONY : src/core.cpp.i

src/core.s: src/core.cpp.s
.PHONY : src/core.s

# target to generate assembly for a file
src/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/core.cpp.s
.PHONY : src/core.cpp.s

src/cpu/ALU.o: src/cpu/ALU.cpp.o
.PHONY : src/cpu/ALU.o

# target to build an object file
src/cpu/ALU.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/cpu/ALU.cpp.o
.PHONY : src/cpu/ALU.cpp.o

src/cpu/ALU.i: src/cpu/ALU.cpp.i
.PHONY : src/cpu/ALU.i

# target to preprocess a source file
src/cpu/ALU.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/cpu/ALU.cpp.i
.PHONY : src/cpu/ALU.cpp.i

src/cpu/ALU.s: src/cpu/ALU.cpp.s
.PHONY : src/cpu/ALU.s

# target to generate assembly for a file
src/cpu/ALU.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/cpu/ALU.cpp.s
.PHONY : src/cpu/ALU.cpp.s

src/cpu/CONTROL_UNIT.o: src/cpu/CONTROL_UNIT.cpp.o
.PHONY : src/cpu/CONTROL_UNIT.o

# target to build an object file
src/cpu/CONTROL_UNIT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/cpu/CONTROL_UNIT.cpp.o
.PHONY : src/cpu/CONTROL_UNIT.cpp.o

src/cpu/CONTROL_UNIT.i: src/cpu/CONTROL_UNIT.cpp.i
.PHONY : src/cpu/CONTROL_UNIT.i

# target to preprocess a source file
src/cpu/CONTROL_UNIT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/cpu/CONTROL_UNIT.cpp.i
.PHONY : src/cpu/CONTROL_UNIT.cpp.i

src/cpu/CONTROL_UNIT.s: src/cpu/CONTROL_UNIT.cpp.s
.PHONY : src/cpu/CONTROL_UNIT.s

# target to generate assembly for a file
src/cpu/CONTROL_UNIT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/cpu/CONTROL_UNIT.cpp.s
.PHONY : src/cpu/CONTROL_UNIT.cpp.s

src/cpu/REGISTER.o: src/cpu/REGISTER.cpp.o
.PHONY : src/cpu/REGISTER.o

# target to build an object file
src/cpu/REGISTER.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/cpu/REGISTER.cpp.o
.PHONY : src/cpu/REGISTER.cpp.o

src/cpu/REGISTER.i: src/cpu/REGISTER.cpp.i
.PHONY : src/cpu/REGISTER.i

# target to preprocess a source file
src/cpu/REGISTER.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/cpu/REGISTER.cpp.i
.PHONY : src/cpu/REGISTER.cpp.i

src/cpu/REGISTER.s: src/cpu/REGISTER.cpp.s
.PHONY : src/cpu/REGISTER.s

# target to generate assembly for a file
src/cpu/REGISTER.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/cpu/REGISTER.cpp.s
.PHONY : src/cpu/REGISTER.cpp.s

src/cpu/REGISTER_BANK.o: src/cpu/REGISTER_BANK.cpp.o
.PHONY : src/cpu/REGISTER_BANK.o

# target to build an object file
src/cpu/REGISTER_BANK.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/cpu/REGISTER_BANK.cpp.o
.PHONY : src/cpu/REGISTER_BANK.cpp.o

src/cpu/REGISTER_BANK.i: src/cpu/REGISTER_BANK.cpp.i
.PHONY : src/cpu/REGISTER_BANK.i

# target to preprocess a source file
src/cpu/REGISTER_BANK.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/cpu/REGISTER_BANK.cpp.i
.PHONY : src/cpu/REGISTER_BANK.cpp.i

src/cpu/REGISTER_BANK.s: src/cpu/REGISTER_BANK.cpp.s
.PHONY : src/cpu/REGISTER_BANK.s

# target to generate assembly for a file
src/cpu/REGISTER_BANK.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/cpu/REGISTER_BANK.cpp.s
.PHONY : src/cpu/REGISTER_BANK.cpp.s

src/loader.o: src/loader.cpp.o
.PHONY : src/loader.o

# target to build an object file
src/loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/loader.cpp.o
.PHONY : src/loader.cpp.o

src/loader.i: src/loader.cpp.i
.PHONY : src/loader.i

# target to preprocess a source file
src/loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/loader.cpp.i
.PHONY : src/loader.cpp.i

src/loader.s: src/loader.cpp.s
.PHONY : src/loader.s

# target to generate assembly for a file
src/loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/loader.cpp.s
.PHONY : src/loader.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/memory/CACHE.o: src/memory/CACHE.cpp.o
.PHONY : src/memory/CACHE.o

# target to build an object file
src/memory/CACHE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/memory/CACHE.cpp.o
.PHONY : src/memory/CACHE.cpp.o

src/memory/CACHE.i: src/memory/CACHE.cpp.i
.PHONY : src/memory/CACHE.i

# target to preprocess a source file
src/memory/CACHE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/memory/CACHE.cpp.i
.PHONY : src/memory/CACHE.cpp.i

src/memory/CACHE.s: src/memory/CACHE.cpp.s
.PHONY : src/memory/CACHE.s

# target to generate assembly for a file
src/memory/CACHE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/memory/CACHE.cpp.s
.PHONY : src/memory/CACHE.cpp.s

src/memory/MAINMEMORY.o: src/memory/MAINMEMORY.cpp.o
.PHONY : src/memory/MAINMEMORY.o

# target to build an object file
src/memory/MAINMEMORY.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/memory/MAINMEMORY.cpp.o
.PHONY : src/memory/MAINMEMORY.cpp.o

src/memory/MAINMEMORY.i: src/memory/MAINMEMORY.cpp.i
.PHONY : src/memory/MAINMEMORY.i

# target to preprocess a source file
src/memory/MAINMEMORY.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/memory/MAINMEMORY.cpp.i
.PHONY : src/memory/MAINMEMORY.cpp.i

src/memory/MAINMEMORY.s: src/memory/MAINMEMORY.cpp.s
.PHONY : src/memory/MAINMEMORY.s

# target to generate assembly for a file
src/memory/MAINMEMORY.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/memory/MAINMEMORY.cpp.s
.PHONY : src/memory/MAINMEMORY.cpp.s

src/memory/MEMORYCELL.o: src/memory/MEMORYCELL.cpp.o
.PHONY : src/memory/MEMORYCELL.o

# target to build an object file
src/memory/MEMORYCELL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/memory/MEMORYCELL.cpp.o
.PHONY : src/memory/MEMORYCELL.cpp.o

src/memory/MEMORYCELL.i: src/memory/MEMORYCELL.cpp.i
.PHONY : src/memory/MEMORYCELL.i

# target to preprocess a source file
src/memory/MEMORYCELL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/memory/MEMORYCELL.cpp.i
.PHONY : src/memory/MEMORYCELL.cpp.i

src/memory/MEMORYCELL.s: src/memory/MEMORYCELL.cpp.s
.PHONY : src/memory/MEMORYCELL.s

# target to generate assembly for a file
src/memory/MEMORYCELL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/memory/MEMORYCELL.cpp.s
.PHONY : src/memory/MEMORYCELL.cpp.s

src/memory/SECONDARY_MEMORY.o: src/memory/SECONDARY_MEMORY.cpp.o
.PHONY : src/memory/SECONDARY_MEMORY.o

# target to build an object file
src/memory/SECONDARY_MEMORY.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/memory/SECONDARY_MEMORY.cpp.o
.PHONY : src/memory/SECONDARY_MEMORY.cpp.o

src/memory/SECONDARY_MEMORY.i: src/memory/SECONDARY_MEMORY.cpp.i
.PHONY : src/memory/SECONDARY_MEMORY.i

# target to preprocess a source file
src/memory/SECONDARY_MEMORY.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/memory/SECONDARY_MEMORY.cpp.i
.PHONY : src/memory/SECONDARY_MEMORY.cpp.i

src/memory/SECONDARY_MEMORY.s: src/memory/SECONDARY_MEMORY.cpp.s
.PHONY : src/memory/SECONDARY_MEMORY.s

# target to generate assembly for a file
src/memory/SECONDARY_MEMORY.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/memory/SECONDARY_MEMORY.cpp.s
.PHONY : src/memory/SECONDARY_MEMORY.cpp.s

src/process.o: src/process.cpp.o
.PHONY : src/process.o

# target to build an object file
src/process.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/process.cpp.o
.PHONY : src/process.cpp.o

src/process.i: src/process.cpp.i
.PHONY : src/process.i

# target to preprocess a source file
src/process.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/process.cpp.i
.PHONY : src/process.cpp.i

src/process.s: src/process.cpp.s
.PHONY : src/process.s

# target to generate assembly for a file
src/process.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CustomVonNeumannMachine.dir/build.make CMakeFiles/CustomVonNeumannMachine.dir/src/process.cpp.s
.PHONY : src/process.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Assembler"
	@echo "... CustomVonNeumannMachine"
	@echo "... assembler/assembler.o"
	@echo "... assembler/assembler.i"
	@echo "... assembler/assembler.s"
	@echo "... src/PCB.o"
	@echo "... src/PCB.i"
	@echo "... src/PCB.s"
	@echo "... src/core.o"
	@echo "... src/core.i"
	@echo "... src/core.s"
	@echo "... src/cpu/ALU.o"
	@echo "... src/cpu/ALU.i"
	@echo "... src/cpu/ALU.s"
	@echo "... src/cpu/CONTROL_UNIT.o"
	@echo "... src/cpu/CONTROL_UNIT.i"
	@echo "... src/cpu/CONTROL_UNIT.s"
	@echo "... src/cpu/REGISTER.o"
	@echo "... src/cpu/REGISTER.i"
	@echo "... src/cpu/REGISTER.s"
	@echo "... src/cpu/REGISTER_BANK.o"
	@echo "... src/cpu/REGISTER_BANK.i"
	@echo "... src/cpu/REGISTER_BANK.s"
	@echo "... src/loader.o"
	@echo "... src/loader.i"
	@echo "... src/loader.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/memory/CACHE.o"
	@echo "... src/memory/CACHE.i"
	@echo "... src/memory/CACHE.s"
	@echo "... src/memory/MAINMEMORY.o"
	@echo "... src/memory/MAINMEMORY.i"
	@echo "... src/memory/MAINMEMORY.s"
	@echo "... src/memory/MEMORYCELL.o"
	@echo "... src/memory/MEMORYCELL.i"
	@echo "... src/memory/MEMORYCELL.s"
	@echo "... src/memory/SECONDARY_MEMORY.o"
	@echo "... src/memory/SECONDARY_MEMORY.i"
	@echo "... src/memory/SECONDARY_MEMORY.s"
	@echo "... src/process.o"
	@echo "... src/process.i"
	@echo "... src/process.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

